### ISSUE TITLE
Add missing dependency on php-symfony-translation for php-twig-extensions

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn-debian/packaging#4]
Add missing dependency on `php-symfony-translation` for `php-twig-extensions `

**Comment by ghost** [comment]
Did you also report this issue upstream?

**Comment by gijzelaerr** [comment]
not sure if it is an issue upstream, have to check

**Comment by gijzelaerr** [comment]
@fkooman the composer file 'suggests' `php-symfony-translation`, so looks like debian doesnt make this a hard requirement. I could add it as a requirement manually. Didn't report upstream.

**Comment by gijzelaerr** [comment]
@fkooman no opinion about this?

**Comment by ghost** [comment]
You created php-twig-extensions, right? And somehow I am using functionality that requires also php-symfony-translation? Then I'd make it a dependency of php-twig-extensions.

**Comment by gijzelaerr** [comment]
I think it might actually be a bug in pkg-php-tools, since `symfony-translation` it isn't picked up as an optional dependency which is the intention of the `php-twig-extensions` developers.

https://bugs.launchpad.net/ubuntu/+source/pkg-php-tools/+bug/1708382

**Comment by gijzelaerr** [comment]
Never mind, that suggest dependency is actually there, closed that bug.

So the author of `php-twig-extensions` thinks `symfony-translation` is a suggested dependency. In the Debian package it is also a suggested dependency.

You can install suggested dependencies like this:
```
$ sudo apt-get --install-suggests install php-twig-extensions
```
Now if your software fails since  `symfony-translation` is not installed, I think the right way to proceed is to add  `symfony-translation` as a hard dependency to your software, and not to the `php-twig-extensions` package.

Closing this issue since I think that is probably the right solution, please reopen if you think otherwise.

**Comment by ghost** [comment]
To run the unit tests you NEED the `symfony/translation` dependency, so they need to be a "BuildRequires" anyway.

For runtime, technically you do not need it, but I don't really understand why it seems to be required then, maybe because of the i18n/gettext stuff?

In CentOS/Fedora the `symfony/translation` is added as a runtime dependency "Requires" to `php-twig-extensions`, not optional.

You can add the `symfony/translation` then as a (required) dependency of vpn-lib-common. I update vpn-lib-common to add it to `composer.json` as well, but won't release a new version.

What do you think?

**Comment by ghost** [comment]
What is also weird is that for development purposes I don't depend on `symfony/translation` and that works really well.

**Comment by gijzelaerr** [comment]
they are a build requirement already. 

Yes, adding it to the `vpn-lib-common` library as a dependency seems to be the right solution.
